# Basic continous integration for sdk-samples
#    Copyright 2023 Labforge Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @author Thomas Reidemeister <thomas@labforge.ca>
#
# To setup a self-hosted runner to test this
# (1) Setup a Windows 10 machine with autologin
# (2) Register a Github actions runner on that machine, run from startup (not as headless service runner)
# (3) Install
#   - VS build tools,
#   - Pleora SDK,
#   - Python 3.10
#   - Git for Windows
# (4) Set up a private backing repository holding proprietary wheels and check this out using a CI token
# (5) Set a repo actions secret for CITOKEN
# (5) Tag that runner as W64HIL
# (6) Allow for executing shell scripts https:/go.microsoft.com/fwlink/?LinkID=135170
name: ContinousIntegration

on:
  push:
    branches: [ ]
  workflow_dispatch:

jobs:

  # See if assumed environment builds on windows
  build_samples:
    runs-on: W64HIL
    steps:
      - name: Check out samples
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - name: Check out private dependencies
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
          repository: labforge/pleora_backing
          token:  ${{ secrets.CITOKEN }}
          path: dependencies
      - name: Setup dependencies
        shell: cmd
        run: |
          .github\workflows\bootstrap.bat
      - name: Install eBUS Python
        shell: cmd
        run: |
          CALL venv\Scripts\activate
          ECHO "Installing eBUS Python"
          pip install dependencies\ebus_python-6.3.0-6343-py310-none-win_amd64.whl

      - name: Build examples
        shell: cmd
        run: |
          call venv\Scripts\activate
          
          REM Build distribution example (depends on most other samples)
          cd distribution
          call build.bat
