# Basic continous integration for sdk-samples
#    Copyright 2023 Labforge Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @author Thomas Reidemeister <thomas@labforge.ca>
#
# To setup a self-hosted runner to test this
# (1) Setup a Windows 10 machine with autologin
# (2) Register a Github actions runner on that machine, run from startup (not as headless service runner)
# (3) Install
#   - VS build tools,
#   - Pleora SDK,
#   - Python 3.10
#   - Git for Windows
# (4) Set up a private backing repository holding proprietary wheels and check this out using a CI token
# (5) Set a repo actions secret for CITOKEN
# (5) Tag that runner as W64HIL
# (6) Allow for executing shell scripts https:/go.microsoft.com/fwlink/?LinkID=135170
name: ContinousIntegration

on:
  push:
    branches: [ ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish_sdk:
    runs-on: HIL
    steps:
    - name: Checkout head for release notes
      uses: actions/checkout@v3
      with:
        lfs: true
        submodules: true
    - name: Generate release notes
      run: |
        git describe --tags --abbrev=0 HEAD | xargs git log -1 --pretty=%B > release.txt
    - name: Stage backing files
      uses: actions/checkout@v3
      with:
        lfs: true
        submodules: true
        repository: labforge/pleora_backing
        token: ${{ secrets.CITOKEN }}
        path: release
    - name: Build SDK documentation to publish
      run: |
        cd release
        ar x eBUS_SDK_Ubuntu-22.04-x86_64-6.3.0-6343.deb
        tar xvzf data.tar.gz
        cd opt/pleora/ebus_sdk/Ubuntu-22.04-x86_64/share/doc/python/
        zip -r9ov ../../../../../../../api_docs.zip *
        cd ../../../../../../../
        # back to root from release
        cd ..
    - name: Assemble Windows SDK
      run: |
        cat release/eBUS_*.exea* > release/eBUS_SDK_Windows-64-bit.exe
    - name: Release Public
      uses: treideme/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: |
          release/*.whl
          release/eBUS_SDK_Windows-64-bit.exe
          release/*.deb
          release/api_docs.zip
        token: ${{ secrets.DEPLOYTOKEN }}
        repository: labforge/bottlenose
        body_path: release.txt

  build_samples:
    runs-on: W64HIL
    steps:
    - name: Check out samples
      uses: actions/checkout@v3
      with:
        lfs: true
        submodules: true
        path: samples
    - name: Build samples
      uses: ./.github/actions/build
      with:
        artifact_name: installer
        token: ${{ secrets.CITOKEN }}
        path: samples
